### ISSUE TITLE
Improvements proposal main window/signal view

### ISSUE THREAD

**Issue by bvernoux** [josevcm/nfc-laboratory#13]
Improvements proposal main window/signal view:
1. In main windows for NfcA or other standard it will be interesting to rename "Cmd" to "Cmd/Answer" (or something similar) so far there is only "Cmd" name example REQA but the answer is empty as for example it is ATQA for NFCA and it will be even better to add that in the main window as we have such details when we click on REQA for example which show clearly REQA and ATQA.
![image](https://user-images.githubusercontent.com/432709/167694695-a58645d2-90ec-4639-9d3d-440af461bafb.png)

1. In main window add events RF field start / RF field stop (can be detected with the level which change...)
Such events will be very useful especially to check quickly the Reader is compliant with the specification which requires to have the field ON during "x ms" before to do data exchange with Tag ...
1. In Signal view
It will be great to add some "user" marker start/stop (which can be moved freely) to display the time in us/ms (depending on range with auto time like you have today) as sometimes it is interesting to check the time between 2 frames directly or even the time since the RF field start (which is not visible in main window)

**Comment by josevcm** [comment]
Hi Benjamin

Thanks for the suggestions, I have included them in the development branch, release comming soon...
