### ISSUE TITLE
I-Block / S-Block mismatch

### ISSUE THREAD

**Issue by gentilkiwi** [josevcm/nfc-laboratory#14]
Hello,

On version 2.8.0, it seems a `S-Block` is interpreted as `I-Block` when receiving from an `I-Block`
On the oppositive way, when receiving an `I-Block` after a `S-Block`, it's not interpreted.

No problem on main listing, but protocol decoding seems to be incorrect.

![image](https://user-images.githubusercontent.com/2307945/173189348-eb8669cb-b43a-402e-8045-44559d53888e.png)
![image](https://user-images.githubusercontent.com/2307945/173189374-8b0a6a19-96c5-4d30-a168-da89a617fabe.png)

**Comment by josevcm** [comment]
Hi Benjamin

Thanks for the information, I just corrected it on the development branch, I will generate a release soon.

Regards

**Comment by gentilkiwi** [comment]
Thank you Jose!

![image](https://user-images.githubusercontent.com/2307945/173230762-e17459cb-7a97-4ed1-a843-340a5dc6508a.png)
