### ISSUE TITLE
divide by zero?

### ISSUE THREAD

**Issue by go2net** [josevcm/nfc-laboratory#19]
in src/nfc-lib/lib-nfc/nfc-decode/src/main/cpp/NfcTech.h, have this code (line 398)

>       float signalDiff = std::abs(signalValue - signalEnvelope) / signalEnvelope;

signalEnvelope been declared as 0 in line 351

>    // signal envelope value
>    float signalEnvelope = 0;

I searched all projects, no place to set value for this variable, when code run to here, you may get divded by zero issue

**Comment by josevcm** [comment]
Hi, yes signalEnvelope is 0 for the first time, but did not produces divide-by-zero error. For IEEE floats this division result is +INF and continue well. 

Thanks for analyzing the code!
