### ISSUE TITLE
may i get the wave data?

### ISSUE THREAD

**Issue by yywei0323** [josevcm/nfc-laboratory#21]
May I ask how can i get the wave data? I found the wave data of "ATQA" ，I wonder if i can get my devices wave data and how.

**Comment by josevcm** [comment]
Hi

By pressing recording buttom you can get raw wave data, the file will be
created insiste installation directory.

 Regards

**Comment by yywei0323** [comment]
I 'm sorry to bother you again. I have tried to press the recording bottom on the left of the tool box. There isn't the wave file in the installation directory as the picture. Besides, after pressing the bottom, i can't presss any bottom of the tool box. Did i operate incorrectly?
![image](https://github.com/josevcm/nfc-laboratory/assets/68979602/8d2f7966-4430-4b54-9bd0-aa7474e689bd)

**Comment by josevcm** [comment]
The "Live" and "Record" buttons are disabled, does the Airspy device work correctly? 
If you have installed the application in "C:\Program Files" it is possible that windows blocks access to disk and does not allow recording, try installing it in another folder.

**Comment by yywei0323** [comment]
Thanks for your in time response ! ！！ (Bow!) 
I have got the wave file. I have filted the ATQA data, and recorded it. Does it mean the signal data in the file only match the "ATQA" command? If not, can i use some method to get the data?
![image](https://github.com/josevcm/nfc-laboratory/assets/68979602/1702b6a3-be50-4236-95a6-3c81a3d478da)

**Comment by josevcm** [comment]
You can zoom-out all capture using mouse well to see complete signal. Your screenshot show REQA in the left, but for some reason is not correctly decoded, you should see the that command at the top, you can try different distances from the antenna and card to get a clear signal.

**Comment by josevcm** [comment]
NFC-LAB does not allow you to cut pieces of the signal, for that you can
open the complete file with Audaticy (https://www.audacityteam.org/) and
extract the parts you need.
