### ISSUE TITLE
nfc-lab v2.1.0 "Filter/Setup"seems to be not implemented

### ISSUE THREAD

**Issue by bvernoux** [josevcm/nfc-laboratory#4]
With nfc-lab v2.1.0 (my own build see https://github.com/josevcm/nfc-laboratory/issues/3) It seems when clicking on the Filter there is no effect (and I do not see where to enter the filter and what are the rules ?)
![image](https://user-images.githubusercontent.com/432709/134768722-5d632bce-ea3c-4468-95c8-1a5e0f094d0b.png)

Also Setup have no effect when we click on it
![image](https://user-images.githubusercontent.com/432709/134768744-64fa3008-b10c-4ac3-ab5e-84496f955ad7.png)

**Comment by josevcm** [comment]
Hi Benjamin


I have to add the user manual....

The filtering function serves to limit the number of identical messages
that are received, it only acts if  is received repeated message many times.

The settings is not implemented yet, sorry!

I will fix at son as posible

**Comment by bvernoux** [comment]
About the Filter:
- Maybe it it will be great to add a real filter supporting also regExp PCRE (like the one supported by default in Qt => QRegExp) ?
- I have done that in my similar NFC sniffer tool see https://github.com/hydrabus/hydratool

**Comment by josevcm** [comment]
Hi Benjamin,

Regexp filtering it's a good improvement, I will add to roadmap.

**Comment by josevcm** [comment]
Hi

Already included in development branch, release soon...

![image](https://user-images.githubusercontent.com/20493965/170856903-31bcd119-3f5d-42ea-9ebf-a56566d17ff3.png)
