### ISSUE TITLE
RTL-SDR not works

### ISSUE THREAD

**Issue by iphizic** [josevcm/nfc-laboratory#44]
I build and run nfc-spy on linux in log see initialization sdr:
```
 Found Rafael Micro R828D tuner
[R82XX] PLL not locked!
Disabled direct sampling mode
[R82XX] PLL not locked!
```
but Acquisition is inactive.

**Comment by Steffen-W** [comment]
Same like #41 but for me the code works. Which sdr are you using?

**Comment by iphizic** [comment]
Thank you, but, I not see signal. If I run sdrpp signal is present. I use rtl-sdr.com dongle v4.

**Comment by josevcm** [comment]
Please set this DEBUG level in the INI file, start the application and send me "nfc-spy.log" to see what happens.

[logger]
root=DEBUG

**Comment by iphizic** [comment]
Where nfc-spy.log located. I can't find him, and when I close application, see segmentation fault in term.

**Comment by josevcm** [comment]
In user home, under ".local/share/josevcm/nfc-spy/log/nfc-spy.log"

**Comment by iphizic** [comment]
[nfc-spy.log](https://github.com/user-attachments/files/17828062/nfc-spy.log)

**Comment by josevcm** [comment]
Please change gainMode=1 an set 12db aprox

**Comment by josevcm** [comment]
I close the issue, if continue the problem, please open a new one.
